// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface CompleteNotifyGatewayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.CompleteNotifyGateway)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes userId = 1;</code>
   * @return The userId.
   */
  com.google.protobuf.ByteString getUserId();

  /**
   * <code>bytes accountId = 2;</code>
   * @return The accountId.
   */
  com.google.protobuf.ByteString getAccountId();

  /**
   * <code>bytes version = 3;</code>
   * @return The version.
   */
  com.google.protobuf.ByteString getVersion();

  /**
   * <code>bytes sendTime = 4;</code>
   * @return The sendTime.
   */
  com.google.protobuf.ByteString getSendTime();

  /**
   * <code>repeated bytes position = 5;</code>
   * @return A list containing the position.
   */
  java.util.List<com.google.protobuf.ByteString> getPositionList();
  /**
   * <code>repeated bytes position = 5;</code>
   * @return The count of position.
   */
  int getPositionCount();
  /**
   * <code>repeated bytes position = 5;</code>
   * @param index The index of the element to return.
   * @return The position at the given index.
   */
  com.google.protobuf.ByteString getPosition(int index);

  /**
   * <code>bytes wallet = 6;</code>
   * @return The wallet.
   */
  com.google.protobuf.ByteString getWallet();
}
