// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface CompleteNotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.CompleteNotify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 accountId = 2;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>int64 version = 3;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>int64 sendTime = 4;</code>
   * @return The sendTime.
   */
  long getSendTime();

  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  java.util.List<com.examples.protobuf.parse.Position> 
      getPositionList();
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  com.examples.protobuf.parse.Position getPosition(int index);
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  int getPositionCount();
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  java.util.List<? extends com.examples.protobuf.parse.PositionOrBuilder> 
      getPositionOrBuilderList();
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  com.examples.protobuf.parse.PositionOrBuilder getPositionOrBuilder(
      int index);

  /**
   * <code>.ref.parse.Wallet wallet = 6;</code>
   * @return Whether the wallet field is set.
   */
  boolean hasWallet();
  /**
   * <code>.ref.parse.Wallet wallet = 6;</code>
   * @return The wallet.
   */
  com.examples.protobuf.parse.Wallet getWallet();
  /**
   * <code>.ref.parse.Wallet wallet = 6;</code>
   */
  com.examples.protobuf.parse.WalletOrBuilder getWalletOrBuilder();
}
