// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

/**
 * Protobuf type {@code ref.parse.CompleteNotify}
 */
public final class CompleteNotify extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ref.parse.CompleteNotify)
    CompleteNotifyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompleteNotify.newBuilder() to construct.
  private CompleteNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompleteNotify() {
    position_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompleteNotify();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompleteNotify(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 16: {

            accountId_ = input.readInt64();
            break;
          }
          case 24: {

            version_ = input.readInt64();
            break;
          }
          case 32: {

            sendTime_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              position_ = new java.util.ArrayList<com.examples.protobuf.parse.Position>();
              mutable_bitField0_ |= 0x00000001;
            }
            position_.add(
                input.readMessage(com.examples.protobuf.parse.Position.parser(), extensionRegistry));
            break;
          }
          case 50: {
            com.examples.protobuf.parse.Wallet.Builder subBuilder = null;
            if (wallet_ != null) {
              subBuilder = wallet_.toBuilder();
            }
            wallet_ = input.readMessage(com.examples.protobuf.parse.Wallet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(wallet_);
              wallet_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        position_ = java.util.Collections.unmodifiableList(position_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.examples.protobuf.parse.Parse.internal_static_ref_parse_CompleteNotify_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.examples.protobuf.parse.Parse.internal_static_ref_parse_CompleteNotify_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.examples.protobuf.parse.CompleteNotify.class, com.examples.protobuf.parse.CompleteNotify.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 2;
  private long accountId_;
  /**
   * <code>int64 accountId = 2;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public long getAccountId() {
    return accountId_;
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private long version_;
  /**
   * <code>int64 version = 3;</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }

  public static final int SENDTIME_FIELD_NUMBER = 4;
  private long sendTime_;
  /**
   * <code>int64 sendTime = 4;</code>
   * @return The sendTime.
   */
  @java.lang.Override
  public long getSendTime() {
    return sendTime_;
  }

  public static final int POSITION_FIELD_NUMBER = 5;
  private java.util.List<com.examples.protobuf.parse.Position> position_;
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.examples.protobuf.parse.Position> getPositionList() {
    return position_;
  }
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.examples.protobuf.parse.PositionOrBuilder> 
      getPositionOrBuilderList() {
    return position_;
  }
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  @java.lang.Override
  public int getPositionCount() {
    return position_.size();
  }
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  @java.lang.Override
  public com.examples.protobuf.parse.Position getPosition(int index) {
    return position_.get(index);
  }
  /**
   * <code>repeated .ref.parse.Position position = 5;</code>
   */
  @java.lang.Override
  public com.examples.protobuf.parse.PositionOrBuilder getPositionOrBuilder(
      int index) {
    return position_.get(index);
  }

  public static final int WALLET_FIELD_NUMBER = 6;
  private com.examples.protobuf.parse.Wallet wallet_;
  /**
   * <code>.ref.parse.Wallet wallet = 6;</code>
   * @return Whether the wallet field is set.
   */
  @java.lang.Override
  public boolean hasWallet() {
    return wallet_ != null;
  }
  /**
   * <code>.ref.parse.Wallet wallet = 6;</code>
   * @return The wallet.
   */
  @java.lang.Override
  public com.examples.protobuf.parse.Wallet getWallet() {
    return wallet_ == null ? com.examples.protobuf.parse.Wallet.getDefaultInstance() : wallet_;
  }
  /**
   * <code>.ref.parse.Wallet wallet = 6;</code>
   */
  @java.lang.Override
  public com.examples.protobuf.parse.WalletOrBuilder getWalletOrBuilder() {
    return getWallet();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (accountId_ != 0L) {
      output.writeInt64(2, accountId_);
    }
    if (version_ != 0L) {
      output.writeInt64(3, version_);
    }
    if (sendTime_ != 0L) {
      output.writeInt64(4, sendTime_);
    }
    for (int i = 0; i < position_.size(); i++) {
      output.writeMessage(5, position_.get(i));
    }
    if (wallet_ != null) {
      output.writeMessage(6, getWallet());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, accountId_);
    }
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, version_);
    }
    if (sendTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, sendTime_);
    }
    for (int i = 0; i < position_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, position_.get(i));
    }
    if (wallet_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getWallet());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.examples.protobuf.parse.CompleteNotify)) {
      return super.equals(obj);
    }
    com.examples.protobuf.parse.CompleteNotify other = (com.examples.protobuf.parse.CompleteNotify) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getAccountId()
        != other.getAccountId()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (getSendTime()
        != other.getSendTime()) return false;
    if (!getPositionList()
        .equals(other.getPositionList())) return false;
    if (hasWallet() != other.hasWallet()) return false;
    if (hasWallet()) {
      if (!getWallet()
          .equals(other.getWallet())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSendTime());
    if (getPositionCount() > 0) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPositionList().hashCode();
    }
    if (hasWallet()) {
      hash = (37 * hash) + WALLET_FIELD_NUMBER;
      hash = (53 * hash) + getWallet().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.parse.CompleteNotify parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.examples.protobuf.parse.CompleteNotify prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ref.parse.CompleteNotify}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ref.parse.CompleteNotify)
      com.examples.protobuf.parse.CompleteNotifyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.examples.protobuf.parse.Parse.internal_static_ref_parse_CompleteNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.examples.protobuf.parse.Parse.internal_static_ref_parse_CompleteNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.examples.protobuf.parse.CompleteNotify.class, com.examples.protobuf.parse.CompleteNotify.Builder.class);
    }

    // Construct using com.examples.protobuf.parse.CompleteNotify.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      accountId_ = 0L;

      version_ = 0L;

      sendTime_ = 0L;

      if (positionBuilder_ == null) {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        positionBuilder_.clear();
      }
      if (walletBuilder_ == null) {
        wallet_ = null;
      } else {
        wallet_ = null;
        walletBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.examples.protobuf.parse.Parse.internal_static_ref_parse_CompleteNotify_descriptor;
    }

    @java.lang.Override
    public com.examples.protobuf.parse.CompleteNotify getDefaultInstanceForType() {
      return com.examples.protobuf.parse.CompleteNotify.getDefaultInstance();
    }

    @java.lang.Override
    public com.examples.protobuf.parse.CompleteNotify build() {
      com.examples.protobuf.parse.CompleteNotify result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.examples.protobuf.parse.CompleteNotify buildPartial() {
      com.examples.protobuf.parse.CompleteNotify result = new com.examples.protobuf.parse.CompleteNotify(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      result.accountId_ = accountId_;
      result.version_ = version_;
      result.sendTime_ = sendTime_;
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          position_ = java.util.Collections.unmodifiableList(position_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (walletBuilder_ == null) {
        result.wallet_ = wallet_;
      } else {
        result.wallet_ = walletBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.examples.protobuf.parse.CompleteNotify) {
        return mergeFrom((com.examples.protobuf.parse.CompleteNotify)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.examples.protobuf.parse.CompleteNotify other) {
      if (other == com.examples.protobuf.parse.CompleteNotify.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      if (other.getSendTime() != 0L) {
        setSendTime(other.getSendTime());
      }
      if (positionBuilder_ == null) {
        if (!other.position_.isEmpty()) {
          if (position_.isEmpty()) {
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePositionIsMutable();
            position_.addAll(other.position_);
          }
          onChanged();
        }
      } else {
        if (!other.position_.isEmpty()) {
          if (positionBuilder_.isEmpty()) {
            positionBuilder_.dispose();
            positionBuilder_ = null;
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000001);
            positionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPositionFieldBuilder() : null;
          } else {
            positionBuilder_.addAllMessages(other.position_);
          }
        }
      }
      if (other.hasWallet()) {
        mergeWallet(other.getWallet());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.examples.protobuf.parse.CompleteNotify parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.examples.protobuf.parse.CompleteNotify) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long accountId_ ;
    /**
     * <code>int64 accountId = 2;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>int64 accountId = 2;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 accountId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private long version_ ;
    /**
     * <code>int64 version = 3;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 3;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0L;
      onChanged();
      return this;
    }

    private long sendTime_ ;
    /**
     * <code>int64 sendTime = 4;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }
    /**
     * <code>int64 sendTime = 4;</code>
     * @param value The sendTime to set.
     * @return This builder for chaining.
     */
    public Builder setSendTime(long value) {
      
      sendTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sendTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendTime() {
      
      sendTime_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.examples.protobuf.parse.Position> position_ =
      java.util.Collections.emptyList();
    private void ensurePositionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        position_ = new java.util.ArrayList<com.examples.protobuf.parse.Position>(position_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.examples.protobuf.parse.Position, com.examples.protobuf.parse.Position.Builder, com.examples.protobuf.parse.PositionOrBuilder> positionBuilder_;

    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public java.util.List<com.examples.protobuf.parse.Position> getPositionList() {
      if (positionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(position_);
      } else {
        return positionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public int getPositionCount() {
      if (positionBuilder_ == null) {
        return position_.size();
      } else {
        return positionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public com.examples.protobuf.parse.Position getPosition(int index) {
      if (positionBuilder_ == null) {
        return position_.get(index);
      } else {
        return positionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder setPosition(
        int index, com.examples.protobuf.parse.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionIsMutable();
        position_.set(index, value);
        onChanged();
      } else {
        positionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder setPosition(
        int index, com.examples.protobuf.parse.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.set(index, builderForValue.build());
        onChanged();
      } else {
        positionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder addPosition(com.examples.protobuf.parse.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionIsMutable();
        position_.add(value);
        onChanged();
      } else {
        positionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder addPosition(
        int index, com.examples.protobuf.parse.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionIsMutable();
        position_.add(index, value);
        onChanged();
      } else {
        positionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder addPosition(
        com.examples.protobuf.parse.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.add(builderForValue.build());
        onChanged();
      } else {
        positionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder addPosition(
        int index, com.examples.protobuf.parse.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.add(index, builderForValue.build());
        onChanged();
      } else {
        positionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder addAllPosition(
        java.lang.Iterable<? extends com.examples.protobuf.parse.Position> values) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, position_);
        onChanged();
      } else {
        positionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        positionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public Builder removePosition(int index) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.remove(index);
        onChanged();
      } else {
        positionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public com.examples.protobuf.parse.Position.Builder getPositionBuilder(
        int index) {
      return getPositionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public com.examples.protobuf.parse.PositionOrBuilder getPositionOrBuilder(
        int index) {
      if (positionBuilder_ == null) {
        return position_.get(index);  } else {
        return positionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public java.util.List<? extends com.examples.protobuf.parse.PositionOrBuilder> 
         getPositionOrBuilderList() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(position_);
      }
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public com.examples.protobuf.parse.Position.Builder addPositionBuilder() {
      return getPositionFieldBuilder().addBuilder(
          com.examples.protobuf.parse.Position.getDefaultInstance());
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public com.examples.protobuf.parse.Position.Builder addPositionBuilder(
        int index) {
      return getPositionFieldBuilder().addBuilder(
          index, com.examples.protobuf.parse.Position.getDefaultInstance());
    }
    /**
     * <code>repeated .ref.parse.Position position = 5;</code>
     */
    public java.util.List<com.examples.protobuf.parse.Position.Builder> 
         getPositionBuilderList() {
      return getPositionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.examples.protobuf.parse.Position, com.examples.protobuf.parse.Position.Builder, com.examples.protobuf.parse.PositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.examples.protobuf.parse.Position, com.examples.protobuf.parse.Position.Builder, com.examples.protobuf.parse.PositionOrBuilder>(
                position_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.examples.protobuf.parse.Wallet wallet_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.examples.protobuf.parse.Wallet, com.examples.protobuf.parse.Wallet.Builder, com.examples.protobuf.parse.WalletOrBuilder> walletBuilder_;
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     * @return Whether the wallet field is set.
     */
    public boolean hasWallet() {
      return walletBuilder_ != null || wallet_ != null;
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     * @return The wallet.
     */
    public com.examples.protobuf.parse.Wallet getWallet() {
      if (walletBuilder_ == null) {
        return wallet_ == null ? com.examples.protobuf.parse.Wallet.getDefaultInstance() : wallet_;
      } else {
        return walletBuilder_.getMessage();
      }
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    public Builder setWallet(com.examples.protobuf.parse.Wallet value) {
      if (walletBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wallet_ = value;
        onChanged();
      } else {
        walletBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    public Builder setWallet(
        com.examples.protobuf.parse.Wallet.Builder builderForValue) {
      if (walletBuilder_ == null) {
        wallet_ = builderForValue.build();
        onChanged();
      } else {
        walletBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    public Builder mergeWallet(com.examples.protobuf.parse.Wallet value) {
      if (walletBuilder_ == null) {
        if (wallet_ != null) {
          wallet_ =
            com.examples.protobuf.parse.Wallet.newBuilder(wallet_).mergeFrom(value).buildPartial();
        } else {
          wallet_ = value;
        }
        onChanged();
      } else {
        walletBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    public Builder clearWallet() {
      if (walletBuilder_ == null) {
        wallet_ = null;
        onChanged();
      } else {
        wallet_ = null;
        walletBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    public com.examples.protobuf.parse.Wallet.Builder getWalletBuilder() {
      
      onChanged();
      return getWalletFieldBuilder().getBuilder();
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    public com.examples.protobuf.parse.WalletOrBuilder getWalletOrBuilder() {
      if (walletBuilder_ != null) {
        return walletBuilder_.getMessageOrBuilder();
      } else {
        return wallet_ == null ?
            com.examples.protobuf.parse.Wallet.getDefaultInstance() : wallet_;
      }
    }
    /**
     * <code>.ref.parse.Wallet wallet = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.examples.protobuf.parse.Wallet, com.examples.protobuf.parse.Wallet.Builder, com.examples.protobuf.parse.WalletOrBuilder> 
        getWalletFieldBuilder() {
      if (walletBuilder_ == null) {
        walletBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.examples.protobuf.parse.Wallet, com.examples.protobuf.parse.Wallet.Builder, com.examples.protobuf.parse.WalletOrBuilder>(
                getWallet(),
                getParentForChildren(),
                isClean());
        wallet_ = null;
      }
      return walletBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ref.parse.CompleteNotify)
  }

  // @@protoc_insertion_point(class_scope:ref.parse.CompleteNotify)
  private static final com.examples.protobuf.parse.CompleteNotify DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.examples.protobuf.parse.CompleteNotify();
  }

  public static com.examples.protobuf.parse.CompleteNotify getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompleteNotify>
      PARSER = new com.google.protobuf.AbstractParser<CompleteNotify>() {
    @java.lang.Override
    public CompleteNotify parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompleteNotify(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompleteNotify> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompleteNotify> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.examples.protobuf.parse.CompleteNotify getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

