// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public final class Parse {
  private Parse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_CompleteNotify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_CompleteNotify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_CompleteNotifyGateway_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_CompleteNotifyGateway_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_Wallet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_Wallet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_SimpleNotifyWithoutTailFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_SimpleNotifyWithoutTailFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_SimpleNotifyWithoutMiddleFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_SimpleNotifyWithoutMiddleFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_SimpleNotifyWithSimplePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_SimpleNotifyWithSimplePosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_SimplePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_SimplePosition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013parse.proto\022\tref.parse\"\240\001\n\016CompleteNot" +
      "ify\022\016\n\006userId\030\001 \001(\003\022\021\n\taccountId\030\002 \001(\003\022\017" +
      "\n\007version\030\003 \001(\003\022\020\n\010sendTime\030\004 \001(\003\022%\n\010pos" +
      "ition\030\005 \003(\0132\023.ref.parse.Position\022!\n\006wall" +
      "et\030\006 \001(\0132\021.ref.parse.Wallet\"\177\n\025CompleteN" +
      "otifyGateway\022\016\n\006userId\030\001 \001(\014\022\021\n\taccountI" +
      "d\030\002 \001(\014\022\017\n\007version\030\003 \001(\014\022\020\n\010sendTime\030\004 \001" +
      "(\014\022\020\n\010position\030\005 \003(\014\022\016\n\006wallet\030\006 \001(\014\"y\n\010" +
      "Position\022\022\n\npositionId\030\001 \001(\003\022\016\n\006symbol\030\002" +
      " \001(\t\022\020\n\010baseCoin\030\003 \001(\t\022\021\n\tquoteCoin\030\004 \001(" +
      "\t\022\022\n\nsettleCoin\030\005 \001(\t\022\020\n\010position\030\006 \001(\t\"" +
      "R\n\006Wallet\022\017\n\007balance\030\001 \001(\003\022\020\n\010baseCoin\030\003" +
      " \001(\t\022\021\n\tquoteCoin\030\004 \001(\t\022\022\n\nsettleCoin\030\005 " +
      "\001(\t\"B\n\035SimpleNotifyWithoutTailFields\022\016\n\006" +
      "userId\030\001 \001(\003\022\021\n\taccountId\030\002 \001(\003\"V\n\037Simpl" +
      "eNotifyWithoutMiddleFields\022\016\n\006userId\030\001 \001" +
      "(\003\022\021\n\taccountId\030\002 \001(\003\022\020\n\010sendTime\030\004 \001(\003\"" +
      "p\n\036SimpleNotifyWithSimplePosition\022\016\n\006use" +
      "rId\030\001 \001(\003\022\021\n\taccountId\030\002 \001(\003\022+\n\010position" +
      "\030\005 \003(\0132\031.ref.parse.SimplePosition\"F\n\016Sim" +
      "plePosition\022\016\n\006symbol\030\002 \001(\t\022\022\n\nsettleCoi" +
      "n\030\005 \001(\t\022\020\n\010position\030\006 \001(\tB\037\n\033com.example" +
      "s.protobuf.parseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ref_parse_CompleteNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ref_parse_CompleteNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_CompleteNotify_descriptor,
        new java.lang.String[] { "UserId", "AccountId", "Version", "SendTime", "Position", "Wallet", });
    internal_static_ref_parse_CompleteNotifyGateway_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ref_parse_CompleteNotifyGateway_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_CompleteNotifyGateway_descriptor,
        new java.lang.String[] { "UserId", "AccountId", "Version", "SendTime", "Position", "Wallet", });
    internal_static_ref_parse_Position_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ref_parse_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_Position_descriptor,
        new java.lang.String[] { "PositionId", "Symbol", "BaseCoin", "QuoteCoin", "SettleCoin", "Position", });
    internal_static_ref_parse_Wallet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ref_parse_Wallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_Wallet_descriptor,
        new java.lang.String[] { "Balance", "BaseCoin", "QuoteCoin", "SettleCoin", });
    internal_static_ref_parse_SimpleNotifyWithoutTailFields_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ref_parse_SimpleNotifyWithoutTailFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_SimpleNotifyWithoutTailFields_descriptor,
        new java.lang.String[] { "UserId", "AccountId", });
    internal_static_ref_parse_SimpleNotifyWithoutMiddleFields_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ref_parse_SimpleNotifyWithoutMiddleFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_SimpleNotifyWithoutMiddleFields_descriptor,
        new java.lang.String[] { "UserId", "AccountId", "SendTime", });
    internal_static_ref_parse_SimpleNotifyWithSimplePosition_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ref_parse_SimpleNotifyWithSimplePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_SimpleNotifyWithSimplePosition_descriptor,
        new java.lang.String[] { "UserId", "AccountId", "Position", });
    internal_static_ref_parse_SimplePosition_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ref_parse_SimplePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_SimplePosition_descriptor,
        new java.lang.String[] { "Symbol", "SettleCoin", "Position", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
