// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 positionId = 1;</code>
   * @return The positionId.
   */
  long getPositionId();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string baseCoin = 3;</code>
   * @return The baseCoin.
   */
  java.lang.String getBaseCoin();
  /**
   * <code>string baseCoin = 3;</code>
   * @return The bytes for baseCoin.
   */
  com.google.protobuf.ByteString
      getBaseCoinBytes();

  /**
   * <code>string quoteCoin = 4;</code>
   * @return The quoteCoin.
   */
  java.lang.String getQuoteCoin();
  /**
   * <code>string quoteCoin = 4;</code>
   * @return The bytes for quoteCoin.
   */
  com.google.protobuf.ByteString
      getQuoteCoinBytes();

  /**
   * <code>string settleCoin = 5;</code>
   * @return The settleCoin.
   */
  java.lang.String getSettleCoin();
  /**
   * <code>string settleCoin = 5;</code>
   * @return The bytes for settleCoin.
   */
  com.google.protobuf.ByteString
      getSettleCoinBytes();

  /**
   * <code>string position = 6;</code>
   * @return The position.
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 6;</code>
   * @return The bytes for position.
   */
  com.google.protobuf.ByteString
      getPositionBytes();
}
