// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface SimplePositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.SimplePosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string settleCoin = 5;</code>
   * @return The settleCoin.
   */
  java.lang.String getSettleCoin();
  /**
   * <code>string settleCoin = 5;</code>
   * @return The bytes for settleCoin.
   */
  com.google.protobuf.ByteString
      getSettleCoinBytes();

  /**
   * <code>string position = 6;</code>
   * @return The position.
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 6;</code>
   * @return The bytes for position.
   */
  com.google.protobuf.ByteString
      getPositionBytes();
}
