// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

/**
 * Protobuf type {@code ref.parse.SimpleNotifyWithSimplePosition}
 */
public final class SimpleNotifyWithSimplePosition extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ref.parse.SimpleNotifyWithSimplePosition)
    SimpleNotifyWithSimplePositionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SimpleNotifyWithSimplePosition.newBuilder() to construct.
  private SimpleNotifyWithSimplePosition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SimpleNotifyWithSimplePosition() {
    position_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SimpleNotifyWithSimplePosition();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SimpleNotifyWithSimplePosition(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 16: {

            accountId_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              position_ = new java.util.ArrayList<com.examples.protobuf.parse.SimplePosition>();
              mutable_bitField0_ |= 0x00000001;
            }
            position_.add(
                input.readMessage(com.examples.protobuf.parse.SimplePosition.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        position_ = java.util.Collections.unmodifiableList(position_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.examples.protobuf.parse.Parse.internal_static_ref_parse_SimpleNotifyWithSimplePosition_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.examples.protobuf.parse.Parse.internal_static_ref_parse_SimpleNotifyWithSimplePosition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.class, com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 2;
  private long accountId_;
  /**
   * <code>int64 accountId = 2;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public long getAccountId() {
    return accountId_;
  }

  public static final int POSITION_FIELD_NUMBER = 5;
  private java.util.List<com.examples.protobuf.parse.SimplePosition> position_;
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.examples.protobuf.parse.SimplePosition> getPositionList() {
    return position_;
  }
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.examples.protobuf.parse.SimplePositionOrBuilder> 
      getPositionOrBuilderList() {
    return position_;
  }
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  @java.lang.Override
  public int getPositionCount() {
    return position_.size();
  }
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  @java.lang.Override
  public com.examples.protobuf.parse.SimplePosition getPosition(int index) {
    return position_.get(index);
  }
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  @java.lang.Override
  public com.examples.protobuf.parse.SimplePositionOrBuilder getPositionOrBuilder(
      int index) {
    return position_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (accountId_ != 0L) {
      output.writeInt64(2, accountId_);
    }
    for (int i = 0; i < position_.size(); i++) {
      output.writeMessage(5, position_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, accountId_);
    }
    for (int i = 0; i < position_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, position_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.examples.protobuf.parse.SimpleNotifyWithSimplePosition)) {
      return super.equals(obj);
    }
    com.examples.protobuf.parse.SimpleNotifyWithSimplePosition other = (com.examples.protobuf.parse.SimpleNotifyWithSimplePosition) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getAccountId()
        != other.getAccountId()) return false;
    if (!getPositionList()
        .equals(other.getPositionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    if (getPositionCount() > 0) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPositionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.examples.protobuf.parse.SimpleNotifyWithSimplePosition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ref.parse.SimpleNotifyWithSimplePosition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ref.parse.SimpleNotifyWithSimplePosition)
      com.examples.protobuf.parse.SimpleNotifyWithSimplePositionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.examples.protobuf.parse.Parse.internal_static_ref_parse_SimpleNotifyWithSimplePosition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.examples.protobuf.parse.Parse.internal_static_ref_parse_SimpleNotifyWithSimplePosition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.class, com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.Builder.class);
    }

    // Construct using com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      accountId_ = 0L;

      if (positionBuilder_ == null) {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        positionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.examples.protobuf.parse.Parse.internal_static_ref_parse_SimpleNotifyWithSimplePosition_descriptor;
    }

    @java.lang.Override
    public com.examples.protobuf.parse.SimpleNotifyWithSimplePosition getDefaultInstanceForType() {
      return com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.getDefaultInstance();
    }

    @java.lang.Override
    public com.examples.protobuf.parse.SimpleNotifyWithSimplePosition build() {
      com.examples.protobuf.parse.SimpleNotifyWithSimplePosition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.examples.protobuf.parse.SimpleNotifyWithSimplePosition buildPartial() {
      com.examples.protobuf.parse.SimpleNotifyWithSimplePosition result = new com.examples.protobuf.parse.SimpleNotifyWithSimplePosition(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      result.accountId_ = accountId_;
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          position_ = java.util.Collections.unmodifiableList(position_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.examples.protobuf.parse.SimpleNotifyWithSimplePosition) {
        return mergeFrom((com.examples.protobuf.parse.SimpleNotifyWithSimplePosition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.examples.protobuf.parse.SimpleNotifyWithSimplePosition other) {
      if (other == com.examples.protobuf.parse.SimpleNotifyWithSimplePosition.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (positionBuilder_ == null) {
        if (!other.position_.isEmpty()) {
          if (position_.isEmpty()) {
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePositionIsMutable();
            position_.addAll(other.position_);
          }
          onChanged();
        }
      } else {
        if (!other.position_.isEmpty()) {
          if (positionBuilder_.isEmpty()) {
            positionBuilder_.dispose();
            positionBuilder_ = null;
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000001);
            positionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPositionFieldBuilder() : null;
          } else {
            positionBuilder_.addAllMessages(other.position_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.examples.protobuf.parse.SimpleNotifyWithSimplePosition parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.examples.protobuf.parse.SimpleNotifyWithSimplePosition) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long accountId_ ;
    /**
     * <code>int64 accountId = 2;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>int64 accountId = 2;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 accountId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.examples.protobuf.parse.SimplePosition> position_ =
      java.util.Collections.emptyList();
    private void ensurePositionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        position_ = new java.util.ArrayList<com.examples.protobuf.parse.SimplePosition>(position_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.examples.protobuf.parse.SimplePosition, com.examples.protobuf.parse.SimplePosition.Builder, com.examples.protobuf.parse.SimplePositionOrBuilder> positionBuilder_;

    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public java.util.List<com.examples.protobuf.parse.SimplePosition> getPositionList() {
      if (positionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(position_);
      } else {
        return positionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public int getPositionCount() {
      if (positionBuilder_ == null) {
        return position_.size();
      } else {
        return positionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public com.examples.protobuf.parse.SimplePosition getPosition(int index) {
      if (positionBuilder_ == null) {
        return position_.get(index);
      } else {
        return positionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder setPosition(
        int index, com.examples.protobuf.parse.SimplePosition value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionIsMutable();
        position_.set(index, value);
        onChanged();
      } else {
        positionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder setPosition(
        int index, com.examples.protobuf.parse.SimplePosition.Builder builderForValue) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.set(index, builderForValue.build());
        onChanged();
      } else {
        positionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder addPosition(com.examples.protobuf.parse.SimplePosition value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionIsMutable();
        position_.add(value);
        onChanged();
      } else {
        positionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder addPosition(
        int index, com.examples.protobuf.parse.SimplePosition value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionIsMutable();
        position_.add(index, value);
        onChanged();
      } else {
        positionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder addPosition(
        com.examples.protobuf.parse.SimplePosition.Builder builderForValue) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.add(builderForValue.build());
        onChanged();
      } else {
        positionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder addPosition(
        int index, com.examples.protobuf.parse.SimplePosition.Builder builderForValue) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.add(index, builderForValue.build());
        onChanged();
      } else {
        positionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder addAllPosition(
        java.lang.Iterable<? extends com.examples.protobuf.parse.SimplePosition> values) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, position_);
        onChanged();
      } else {
        positionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        positionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public Builder removePosition(int index) {
      if (positionBuilder_ == null) {
        ensurePositionIsMutable();
        position_.remove(index);
        onChanged();
      } else {
        positionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public com.examples.protobuf.parse.SimplePosition.Builder getPositionBuilder(
        int index) {
      return getPositionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public com.examples.protobuf.parse.SimplePositionOrBuilder getPositionOrBuilder(
        int index) {
      if (positionBuilder_ == null) {
        return position_.get(index);  } else {
        return positionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public java.util.List<? extends com.examples.protobuf.parse.SimplePositionOrBuilder> 
         getPositionOrBuilderList() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(position_);
      }
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public com.examples.protobuf.parse.SimplePosition.Builder addPositionBuilder() {
      return getPositionFieldBuilder().addBuilder(
          com.examples.protobuf.parse.SimplePosition.getDefaultInstance());
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public com.examples.protobuf.parse.SimplePosition.Builder addPositionBuilder(
        int index) {
      return getPositionFieldBuilder().addBuilder(
          index, com.examples.protobuf.parse.SimplePosition.getDefaultInstance());
    }
    /**
     * <code>repeated .ref.parse.SimplePosition position = 5;</code>
     */
    public java.util.List<com.examples.protobuf.parse.SimplePosition.Builder> 
         getPositionBuilderList() {
      return getPositionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.examples.protobuf.parse.SimplePosition, com.examples.protobuf.parse.SimplePosition.Builder, com.examples.protobuf.parse.SimplePositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.examples.protobuf.parse.SimplePosition, com.examples.protobuf.parse.SimplePosition.Builder, com.examples.protobuf.parse.SimplePositionOrBuilder>(
                position_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ref.parse.SimpleNotifyWithSimplePosition)
  }

  // @@protoc_insertion_point(class_scope:ref.parse.SimpleNotifyWithSimplePosition)
  private static final com.examples.protobuf.parse.SimpleNotifyWithSimplePosition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.examples.protobuf.parse.SimpleNotifyWithSimplePosition();
  }

  public static com.examples.protobuf.parse.SimpleNotifyWithSimplePosition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SimpleNotifyWithSimplePosition>
      PARSER = new com.google.protobuf.AbstractParser<SimpleNotifyWithSimplePosition>() {
    @java.lang.Override
    public SimpleNotifyWithSimplePosition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SimpleNotifyWithSimplePosition(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SimpleNotifyWithSimplePosition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SimpleNotifyWithSimplePosition> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.examples.protobuf.parse.SimpleNotifyWithSimplePosition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

