// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface SimpleNotifyWithoutTailFieldsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.SimpleNotifyWithoutTailFields)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 accountId = 2;</code>
   * @return The accountId.
   */
  long getAccountId();
}
