// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface SimpleNotifyWithSimplePositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.SimpleNotifyWithSimplePosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 accountId = 2;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  java.util.List<com.examples.protobuf.parse.SimplePosition> 
      getPositionList();
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  com.examples.protobuf.parse.SimplePosition getPosition(int index);
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  int getPositionCount();
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  java.util.List<? extends com.examples.protobuf.parse.SimplePositionOrBuilder> 
      getPositionOrBuilderList();
  /**
   * <code>repeated .ref.parse.SimplePosition position = 5;</code>
   */
  com.examples.protobuf.parse.SimplePositionOrBuilder getPositionOrBuilder(
      int index);
}
