// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package com.examples.protobuf.parse;

public interface SimpleNotifyWithoutMiddleFieldsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.SimpleNotifyWithoutMiddleFields)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 accountId = 2;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>int64 sendTime = 4;</code>
   * @return The sendTime.
   */
  long getSendTime();
}
