// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

package com.examples.protobuf.map;

/**
 * Protobuf enum {@code ref.parse.EnumType}
 */
public enum EnumType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>A = 0;</code>
   */
  A(0),
  /**
   * <code>B = 1;</code>
   */
  B(1),
  /**
   * <code>C = 2;</code>
   */
  C(2),
  /**
   * <code>D = 4;</code>
   */
  D(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>A = 0;</code>
   */
  public static final int A_VALUE = 0;
  /**
   * <code>B = 1;</code>
   */
  public static final int B_VALUE = 1;
  /**
   * <code>C = 2;</code>
   */
  public static final int C_VALUE = 2;
  /**
   * <code>D = 4;</code>
   */
  public static final int D_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnumType forNumber(int value) {
    switch (value) {
      case 0: return A;
      case 1: return B;
      case 2: return C;
      case 4: return D;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumType>() {
          public EnumType findValueByNumber(int number) {
            return EnumType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.examples.protobuf.map.Map.getDescriptor().getEnumTypes().get(0);
  }

  private static final EnumType[] VALUES = values();

  public static EnumType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ref.parse.EnumType)
}

