// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

package com.examples.protobuf.map;

public final class Map {
  private Map() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MessageType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MessageType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_BoolValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_BoolValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_StringValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_StringValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_BytesValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_BytesValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_Int32ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_Int32ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_Fixed32ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_Fixed32ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_Uint32ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_Uint32ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_Int64ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_Int64ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_Fixed64ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_Fixed64ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_Uint64ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_Uint64ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_FloatValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_FloatValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_DoubleValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_DoubleValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_EnumValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_EnumValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_MapMessageType_ReferenceValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_MapMessageType_ReferenceValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_ListMessageType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_ListMessageType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_ReferenceMessageType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_ReferenceMessageType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ref_parse_ReferenceMessageType_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ref_parse_ReferenceMessageType_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmap.proto\022\tref.parse\032\037google/protobuf/" +
      "timestamp.proto\"\321\002\n\013MessageType\022\021\n\tboolV" +
      "alue\030\001 \001(\010\022\023\n\013stringValue\030\002 \001(\t\022\022\n\nbytes" +
      "Value\030\003 \001(\014\022\022\n\nint32Value\030\004 \001(\005\022\024\n\014fixed" +
      "32Value\030\005 \001(\007\022\023\n\013uint32Value\030\006 \001(\r\022\022\n\nin" +
      "t64Value\030\007 \001(\003\022\024\n\014fixed64Value\030\010 \001(\006\022\023\n\013" +
      "uint64Value\030\t \001(\004\022\022\n\nfloatValue\030\n \001(\002\022\023\n" +
      "\013doubleValue\030\013 \001(\001\022&\n\tenumValue\030\014 \001(\0162\023." +
      "ref.parse.EnumType\0227\n\016referenceValue\030\r \001" +
      "(\0132\037.ref.parse.ReferenceMessageType\"\256\014\n\016" +
      "MapMessageType\022;\n\tboolValue\030\001 \003(\0132(.ref." +
      "parse.MapMessageType.BoolValueEntry\022?\n\013s" +
      "tringValue\030\002 \003(\0132*.ref.parse.MapMessageT" +
      "ype.StringValueEntry\022=\n\nbytesValue\030\003 \003(\013" +
      "2).ref.parse.MapMessageType.BytesValueEn" +
      "try\022=\n\nint32Value\030\004 \003(\0132).ref.parse.MapM" +
      "essageType.Int32ValueEntry\022A\n\014fixed32Val" +
      "ue\030\005 \003(\0132+.ref.parse.MapMessageType.Fixe" +
      "d32ValueEntry\022?\n\013uint32Value\030\006 \003(\0132*.ref" +
      ".parse.MapMessageType.Uint32ValueEntry\022=" +
      "\n\nint64Value\030\007 \003(\0132).ref.parse.MapMessag" +
      "eType.Int64ValueEntry\022A\n\014fixed64Value\030\010 " +
      "\003(\0132+.ref.parse.MapMessageType.Fixed64Va" +
      "lueEntry\022?\n\013uint64Value\030\t \003(\0132*.ref.pars" +
      "e.MapMessageType.Uint64ValueEntry\022=\n\nflo" +
      "atValue\030\n \003(\0132).ref.parse.MapMessageType" +
      ".FloatValueEntry\022?\n\013doubleValue\030\013 \003(\0132*." +
      "ref.parse.MapMessageType.DoubleValueEntr" +
      "y\022;\n\tenumValue\030\014 \003(\0132(.ref.parse.MapMess" +
      "ageType.EnumValueEntry\022E\n\016referenceValue" +
      "\030\r \003(\0132-.ref.parse.MapMessageType.Refere" +
      "nceValueEntry\0320\n\016BoolValueEntry\022\013\n\003key\030\001" +
      " \001(\010\022\r\n\005value\030\002 \001(\010:\0028\001\0322\n\020StringValueEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0321\n\017B" +
      "ytesValueEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\014:\0028\001\0321\n\017Int32ValueEntry\022\013\n\003key\030\001 \001(\005\022\r" +
      "\n\005value\030\002 \001(\005:\0028\001\0323\n\021Fixed32ValueEntry\022\013" +
      "\n\003key\030\001 \001(\007\022\r\n\005value\030\002 \001(\007:\0028\001\0322\n\020Uint32" +
      "ValueEntry\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002 \001(\r:\002" +
      "8\001\0321\n\017Int64ValueEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005va" +
      "lue\030\002 \001(\003:\0028\001\0323\n\021Fixed64ValueEntry\022\013\n\003ke" +
      "y\030\001 \001(\006\022\r\n\005value\030\002 \001(\006:\0028\001\0322\n\020Uint64Valu" +
      "eEntry\022\013\n\003key\030\001 \001(\004\022\r\n\005value\030\002 \001(\004:\0028\001\0321" +
      "\n\017FloatValueEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\002:\0028\001\0322\n\020DoubleValueEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\001:\0028\001\032E\n\016EnumValueEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\"\n\005value\030\002 \001(\0162\023.ref.parse." +
      "EnumType:\0028\001\032V\n\023ReferenceValueEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022.\n\005value\030\002 \001(\0132\037.ref.parse.Refe" +
      "renceMessageType:\0028\001\"\325\002\n\017ListMessageType" +
      "\022\021\n\tboolValue\030\001 \003(\010\022\023\n\013stringValue\030\002 \003(\t" +
      "\022\022\n\nbytesValue\030\003 \003(\014\022\022\n\nint32Value\030\004 \003(\005" +
      "\022\024\n\014fixed32Value\030\005 \003(\007\022\023\n\013uint32Value\030\006 " +
      "\003(\r\022\022\n\nint64Value\030\007 \003(\003\022\024\n\014fixed64Value\030" +
      "\010 \003(\006\022\023\n\013uint64Value\030\t \003(\004\022\022\n\nfloatValue" +
      "\030\n \003(\002\022\023\n\013doubleValue\030\013 \003(\001\022&\n\tenumValue" +
      "\030\014 \003(\0162\023.ref.parse.EnumType\0227\n\016reference" +
      "Value\030\r \003(\0132\037.ref.parse.ReferenceMessage" +
      "Type\"\227\001\n\024ReferenceMessageType\022\016\n\006string\030" +
      "\001 \001(\t\022\014\n\004list\030\002 \003(\t\0225\n\003map\030\003 \003(\0132(.ref.p" +
      "arse.ReferenceMessageType.MapEntry\032*\n\010Ma" +
      "pEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*&" +
      "\n\010EnumType\022\005\n\001A\020\000\022\005\n\001B\020\001\022\005\n\001C\020\002\022\005\n\001D\020\004B\035" +
      "\n\031com.examples.protobuf.mapP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ref_parse_MessageType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ref_parse_MessageType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MessageType_descriptor,
        new java.lang.String[] { "BoolValue", "StringValue", "BytesValue", "Int32Value", "Fixed32Value", "Uint32Value", "Int64Value", "Fixed64Value", "Uint64Value", "FloatValue", "DoubleValue", "EnumValue", "ReferenceValue", });
    internal_static_ref_parse_MapMessageType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ref_parse_MapMessageType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_descriptor,
        new java.lang.String[] { "BoolValue", "StringValue", "BytesValue", "Int32Value", "Fixed32Value", "Uint32Value", "Int64Value", "Fixed64Value", "Uint64Value", "FloatValue", "DoubleValue", "EnumValue", "ReferenceValue", });
    internal_static_ref_parse_MapMessageType_BoolValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(0);
    internal_static_ref_parse_MapMessageType_BoolValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_BoolValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_StringValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(1);
    internal_static_ref_parse_MapMessageType_StringValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_StringValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_BytesValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(2);
    internal_static_ref_parse_MapMessageType_BytesValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_BytesValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_Int32ValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(3);
    internal_static_ref_parse_MapMessageType_Int32ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_Int32ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_Fixed32ValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(4);
    internal_static_ref_parse_MapMessageType_Fixed32ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_Fixed32ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_Uint32ValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(5);
    internal_static_ref_parse_MapMessageType_Uint32ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_Uint32ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_Int64ValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(6);
    internal_static_ref_parse_MapMessageType_Int64ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_Int64ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_Fixed64ValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(7);
    internal_static_ref_parse_MapMessageType_Fixed64ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_Fixed64ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_Uint64ValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(8);
    internal_static_ref_parse_MapMessageType_Uint64ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_Uint64ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_FloatValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(9);
    internal_static_ref_parse_MapMessageType_FloatValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_FloatValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_DoubleValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(10);
    internal_static_ref_parse_MapMessageType_DoubleValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_DoubleValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_EnumValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(11);
    internal_static_ref_parse_MapMessageType_EnumValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_EnumValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_MapMessageType_ReferenceValueEntry_descriptor =
      internal_static_ref_parse_MapMessageType_descriptor.getNestedTypes().get(12);
    internal_static_ref_parse_MapMessageType_ReferenceValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_MapMessageType_ReferenceValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ref_parse_ListMessageType_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ref_parse_ListMessageType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_ListMessageType_descriptor,
        new java.lang.String[] { "BoolValue", "StringValue", "BytesValue", "Int32Value", "Fixed32Value", "Uint32Value", "Int64Value", "Fixed64Value", "Uint64Value", "FloatValue", "DoubleValue", "EnumValue", "ReferenceValue", });
    internal_static_ref_parse_ReferenceMessageType_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ref_parse_ReferenceMessageType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_ReferenceMessageType_descriptor,
        new java.lang.String[] { "String", "List", "Map", });
    internal_static_ref_parse_ReferenceMessageType_MapEntry_descriptor =
      internal_static_ref_parse_ReferenceMessageType_descriptor.getNestedTypes().get(0);
    internal_static_ref_parse_ReferenceMessageType_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ref_parse_ReferenceMessageType_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
