// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

package com.examples.protobuf.map;

public interface MessageTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ref.parse.MessageType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool boolValue = 1;</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>string stringValue = 2;</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string stringValue = 2;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>bytes bytesValue = 3;</code>
   * @return The bytesValue.
   */
  com.google.protobuf.ByteString getBytesValue();

  /**
   * <code>int32 int32Value = 4;</code>
   * @return The int32Value.
   */
  int getInt32Value();

  /**
   * <code>fixed32 fixed32Value = 5;</code>
   * @return The fixed32Value.
   */
  int getFixed32Value();

  /**
   * <code>uint32 uint32Value = 6;</code>
   * @return The uint32Value.
   */
  int getUint32Value();

  /**
   * <code>int64 int64Value = 7;</code>
   * @return The int64Value.
   */
  long getInt64Value();

  /**
   * <code>fixed64 fixed64Value = 8;</code>
   * @return The fixed64Value.
   */
  long getFixed64Value();

  /**
   * <code>uint64 uint64Value = 9;</code>
   * @return The uint64Value.
   */
  long getUint64Value();

  /**
   * <code>float floatValue = 10;</code>
   * @return The floatValue.
   */
  float getFloatValue();

  /**
   * <code>double doubleValue = 11;</code>
   * @return The doubleValue.
   */
  double getDoubleValue();

  /**
   * <code>.ref.parse.EnumType enumValue = 12;</code>
   * @return The enum numeric value on the wire for enumValue.
   */
  int getEnumValueValue();
  /**
   * <code>.ref.parse.EnumType enumValue = 12;</code>
   * @return The enumValue.
   */
  com.examples.protobuf.map.EnumType getEnumValue();

  /**
   * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
   * @return Whether the referenceValue field is set.
   */
  boolean hasReferenceValue();
  /**
   * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
   * @return The referenceValue.
   */
  com.examples.protobuf.map.ReferenceMessageType getReferenceValue();
  /**
   * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
   */
  com.examples.protobuf.map.ReferenceMessageTypeOrBuilder getReferenceValueOrBuilder();
}
