// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

package com.examples.protobuf.map;

/**
 * Protobuf type {@code ref.parse.MessageType}
 */
public final class MessageType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ref.parse.MessageType)
    MessageTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageType.newBuilder() to construct.
  private MessageType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageType() {
    stringValue_ = "";
    bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    enumValue_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageType();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            boolValue_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            stringValue_ = s;
            break;
          }
          case 26: {

            bytesValue_ = input.readBytes();
            break;
          }
          case 32: {

            int32Value_ = input.readInt32();
            break;
          }
          case 45: {

            fixed32Value_ = input.readFixed32();
            break;
          }
          case 48: {

            uint32Value_ = input.readUInt32();
            break;
          }
          case 56: {

            int64Value_ = input.readInt64();
            break;
          }
          case 65: {

            fixed64Value_ = input.readFixed64();
            break;
          }
          case 72: {

            uint64Value_ = input.readUInt64();
            break;
          }
          case 85: {

            floatValue_ = input.readFloat();
            break;
          }
          case 89: {

            doubleValue_ = input.readDouble();
            break;
          }
          case 96: {
            int rawValue = input.readEnum();

            enumValue_ = rawValue;
            break;
          }
          case 106: {
            com.examples.protobuf.map.ReferenceMessageType.Builder subBuilder = null;
            if (referenceValue_ != null) {
              subBuilder = referenceValue_.toBuilder();
            }
            referenceValue_ = input.readMessage(com.examples.protobuf.map.ReferenceMessageType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(referenceValue_);
              referenceValue_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.examples.protobuf.map.Map.internal_static_ref_parse_MessageType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.examples.protobuf.map.Map.internal_static_ref_parse_MessageType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.examples.protobuf.map.MessageType.class, com.examples.protobuf.map.MessageType.Builder.class);
  }

  public static final int BOOLVALUE_FIELD_NUMBER = 1;
  private boolean boolValue_;
  /**
   * <code>bool boolValue = 1;</code>
   * @return The boolValue.
   */
  @java.lang.Override
  public boolean getBoolValue() {
    return boolValue_;
  }

  public static final int STRINGVALUE_FIELD_NUMBER = 2;
  private volatile java.lang.Object stringValue_;
  /**
   * <code>string stringValue = 2;</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public java.lang.String getStringValue() {
    java.lang.Object ref = stringValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringValue_ = s;
      return s;
    }
  }
  /**
   * <code>string stringValue = 2;</code>
   * @return The bytes for stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = stringValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTESVALUE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString bytesValue_;
  /**
   * <code>bytes bytesValue = 3;</code>
   * @return The bytesValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesValue() {
    return bytesValue_;
  }

  public static final int INT32VALUE_FIELD_NUMBER = 4;
  private int int32Value_;
  /**
   * <code>int32 int32Value = 4;</code>
   * @return The int32Value.
   */
  @java.lang.Override
  public int getInt32Value() {
    return int32Value_;
  }

  public static final int FIXED32VALUE_FIELD_NUMBER = 5;
  private int fixed32Value_;
  /**
   * <code>fixed32 fixed32Value = 5;</code>
   * @return The fixed32Value.
   */
  @java.lang.Override
  public int getFixed32Value() {
    return fixed32Value_;
  }

  public static final int UINT32VALUE_FIELD_NUMBER = 6;
  private int uint32Value_;
  /**
   * <code>uint32 uint32Value = 6;</code>
   * @return The uint32Value.
   */
  @java.lang.Override
  public int getUint32Value() {
    return uint32Value_;
  }

  public static final int INT64VALUE_FIELD_NUMBER = 7;
  private long int64Value_;
  /**
   * <code>int64 int64Value = 7;</code>
   * @return The int64Value.
   */
  @java.lang.Override
  public long getInt64Value() {
    return int64Value_;
  }

  public static final int FIXED64VALUE_FIELD_NUMBER = 8;
  private long fixed64Value_;
  /**
   * <code>fixed64 fixed64Value = 8;</code>
   * @return The fixed64Value.
   */
  @java.lang.Override
  public long getFixed64Value() {
    return fixed64Value_;
  }

  public static final int UINT64VALUE_FIELD_NUMBER = 9;
  private long uint64Value_;
  /**
   * <code>uint64 uint64Value = 9;</code>
   * @return The uint64Value.
   */
  @java.lang.Override
  public long getUint64Value() {
    return uint64Value_;
  }

  public static final int FLOATVALUE_FIELD_NUMBER = 10;
  private float floatValue_;
  /**
   * <code>float floatValue = 10;</code>
   * @return The floatValue.
   */
  @java.lang.Override
  public float getFloatValue() {
    return floatValue_;
  }

  public static final int DOUBLEVALUE_FIELD_NUMBER = 11;
  private double doubleValue_;
  /**
   * <code>double doubleValue = 11;</code>
   * @return The doubleValue.
   */
  @java.lang.Override
  public double getDoubleValue() {
    return doubleValue_;
  }

  public static final int ENUMVALUE_FIELD_NUMBER = 12;
  private int enumValue_;
  /**
   * <code>.ref.parse.EnumType enumValue = 12;</code>
   * @return The enum numeric value on the wire for enumValue.
   */
  @java.lang.Override public int getEnumValueValue() {
    return enumValue_;
  }
  /**
   * <code>.ref.parse.EnumType enumValue = 12;</code>
   * @return The enumValue.
   */
  @java.lang.Override public com.examples.protobuf.map.EnumType getEnumValue() {
    @SuppressWarnings("deprecation")
    com.examples.protobuf.map.EnumType result = com.examples.protobuf.map.EnumType.valueOf(enumValue_);
    return result == null ? com.examples.protobuf.map.EnumType.UNRECOGNIZED : result;
  }

  public static final int REFERENCEVALUE_FIELD_NUMBER = 13;
  private com.examples.protobuf.map.ReferenceMessageType referenceValue_;
  /**
   * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
   * @return Whether the referenceValue field is set.
   */
  @java.lang.Override
  public boolean hasReferenceValue() {
    return referenceValue_ != null;
  }
  /**
   * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
   * @return The referenceValue.
   */
  @java.lang.Override
  public com.examples.protobuf.map.ReferenceMessageType getReferenceValue() {
    return referenceValue_ == null ? com.examples.protobuf.map.ReferenceMessageType.getDefaultInstance() : referenceValue_;
  }
  /**
   * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
   */
  @java.lang.Override
  public com.examples.protobuf.map.ReferenceMessageTypeOrBuilder getReferenceValueOrBuilder() {
    return getReferenceValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (boolValue_ != false) {
      output.writeBool(1, boolValue_);
    }
    if (!getStringValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringValue_);
    }
    if (!bytesValue_.isEmpty()) {
      output.writeBytes(3, bytesValue_);
    }
    if (int32Value_ != 0) {
      output.writeInt32(4, int32Value_);
    }
    if (fixed32Value_ != 0) {
      output.writeFixed32(5, fixed32Value_);
    }
    if (uint32Value_ != 0) {
      output.writeUInt32(6, uint32Value_);
    }
    if (int64Value_ != 0L) {
      output.writeInt64(7, int64Value_);
    }
    if (fixed64Value_ != 0L) {
      output.writeFixed64(8, fixed64Value_);
    }
    if (uint64Value_ != 0L) {
      output.writeUInt64(9, uint64Value_);
    }
    if (floatValue_ != 0F) {
      output.writeFloat(10, floatValue_);
    }
    if (doubleValue_ != 0D) {
      output.writeDouble(11, doubleValue_);
    }
    if (enumValue_ != com.examples.protobuf.map.EnumType.A.getNumber()) {
      output.writeEnum(12, enumValue_);
    }
    if (referenceValue_ != null) {
      output.writeMessage(13, getReferenceValue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (boolValue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, boolValue_);
    }
    if (!getStringValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringValue_);
    }
    if (!bytesValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, bytesValue_);
    }
    if (int32Value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, int32Value_);
    }
    if (fixed32Value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(5, fixed32Value_);
    }
    if (uint32Value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, uint32Value_);
    }
    if (int64Value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, int64Value_);
    }
    if (fixed64Value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(8, fixed64Value_);
    }
    if (uint64Value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, uint64Value_);
    }
    if (floatValue_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, floatValue_);
    }
    if (doubleValue_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, doubleValue_);
    }
    if (enumValue_ != com.examples.protobuf.map.EnumType.A.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, enumValue_);
    }
    if (referenceValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getReferenceValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.examples.protobuf.map.MessageType)) {
      return super.equals(obj);
    }
    com.examples.protobuf.map.MessageType other = (com.examples.protobuf.map.MessageType) obj;

    if (getBoolValue()
        != other.getBoolValue()) return false;
    if (!getStringValue()
        .equals(other.getStringValue())) return false;
    if (!getBytesValue()
        .equals(other.getBytesValue())) return false;
    if (getInt32Value()
        != other.getInt32Value()) return false;
    if (getFixed32Value()
        != other.getFixed32Value()) return false;
    if (getUint32Value()
        != other.getUint32Value()) return false;
    if (getInt64Value()
        != other.getInt64Value()) return false;
    if (getFixed64Value()
        != other.getFixed64Value()) return false;
    if (getUint64Value()
        != other.getUint64Value()) return false;
    if (java.lang.Float.floatToIntBits(getFloatValue())
        != java.lang.Float.floatToIntBits(
            other.getFloatValue())) return false;
    if (java.lang.Double.doubleToLongBits(getDoubleValue())
        != java.lang.Double.doubleToLongBits(
            other.getDoubleValue())) return false;
    if (enumValue_ != other.enumValue_) return false;
    if (hasReferenceValue() != other.hasReferenceValue()) return false;
    if (hasReferenceValue()) {
      if (!getReferenceValue()
          .equals(other.getReferenceValue())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolValue());
    hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getStringValue().hashCode();
    hash = (37 * hash) + BYTESVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getBytesValue().hashCode();
    hash = (37 * hash) + INT32VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getInt32Value();
    hash = (37 * hash) + FIXED32VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getFixed32Value();
    hash = (37 * hash) + UINT32VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getUint32Value();
    hash = (37 * hash) + INT64VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInt64Value());
    hash = (37 * hash) + FIXED64VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFixed64Value());
    hash = (37 * hash) + UINT64VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUint64Value());
    hash = (37 * hash) + FLOATVALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloatValue());
    hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDoubleValue()));
    hash = (37 * hash) + ENUMVALUE_FIELD_NUMBER;
    hash = (53 * hash) + enumValue_;
    if (hasReferenceValue()) {
      hash = (37 * hash) + REFERENCEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.examples.protobuf.map.MessageType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.map.MessageType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.map.MessageType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.map.MessageType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.examples.protobuf.map.MessageType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ref.parse.MessageType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ref.parse.MessageType)
      com.examples.protobuf.map.MessageTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.examples.protobuf.map.Map.internal_static_ref_parse_MessageType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.examples.protobuf.map.Map.internal_static_ref_parse_MessageType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.examples.protobuf.map.MessageType.class, com.examples.protobuf.map.MessageType.Builder.class);
    }

    // Construct using com.examples.protobuf.map.MessageType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      boolValue_ = false;

      stringValue_ = "";

      bytesValue_ = com.google.protobuf.ByteString.EMPTY;

      int32Value_ = 0;

      fixed32Value_ = 0;

      uint32Value_ = 0;

      int64Value_ = 0L;

      fixed64Value_ = 0L;

      uint64Value_ = 0L;

      floatValue_ = 0F;

      doubleValue_ = 0D;

      enumValue_ = 0;

      if (referenceValueBuilder_ == null) {
        referenceValue_ = null;
      } else {
        referenceValue_ = null;
        referenceValueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.examples.protobuf.map.Map.internal_static_ref_parse_MessageType_descriptor;
    }

    @java.lang.Override
    public com.examples.protobuf.map.MessageType getDefaultInstanceForType() {
      return com.examples.protobuf.map.MessageType.getDefaultInstance();
    }

    @java.lang.Override
    public com.examples.protobuf.map.MessageType build() {
      com.examples.protobuf.map.MessageType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.examples.protobuf.map.MessageType buildPartial() {
      com.examples.protobuf.map.MessageType result = new com.examples.protobuf.map.MessageType(this);
      result.boolValue_ = boolValue_;
      result.stringValue_ = stringValue_;
      result.bytesValue_ = bytesValue_;
      result.int32Value_ = int32Value_;
      result.fixed32Value_ = fixed32Value_;
      result.uint32Value_ = uint32Value_;
      result.int64Value_ = int64Value_;
      result.fixed64Value_ = fixed64Value_;
      result.uint64Value_ = uint64Value_;
      result.floatValue_ = floatValue_;
      result.doubleValue_ = doubleValue_;
      result.enumValue_ = enumValue_;
      if (referenceValueBuilder_ == null) {
        result.referenceValue_ = referenceValue_;
      } else {
        result.referenceValue_ = referenceValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.examples.protobuf.map.MessageType) {
        return mergeFrom((com.examples.protobuf.map.MessageType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.examples.protobuf.map.MessageType other) {
      if (other == com.examples.protobuf.map.MessageType.getDefaultInstance()) return this;
      if (other.getBoolValue() != false) {
        setBoolValue(other.getBoolValue());
      }
      if (!other.getStringValue().isEmpty()) {
        stringValue_ = other.stringValue_;
        onChanged();
      }
      if (other.getBytesValue() != com.google.protobuf.ByteString.EMPTY) {
        setBytesValue(other.getBytesValue());
      }
      if (other.getInt32Value() != 0) {
        setInt32Value(other.getInt32Value());
      }
      if (other.getFixed32Value() != 0) {
        setFixed32Value(other.getFixed32Value());
      }
      if (other.getUint32Value() != 0) {
        setUint32Value(other.getUint32Value());
      }
      if (other.getInt64Value() != 0L) {
        setInt64Value(other.getInt64Value());
      }
      if (other.getFixed64Value() != 0L) {
        setFixed64Value(other.getFixed64Value());
      }
      if (other.getUint64Value() != 0L) {
        setUint64Value(other.getUint64Value());
      }
      if (other.getFloatValue() != 0F) {
        setFloatValue(other.getFloatValue());
      }
      if (other.getDoubleValue() != 0D) {
        setDoubleValue(other.getDoubleValue());
      }
      if (other.enumValue_ != 0) {
        setEnumValueValue(other.getEnumValueValue());
      }
      if (other.hasReferenceValue()) {
        mergeReferenceValue(other.getReferenceValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.examples.protobuf.map.MessageType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.examples.protobuf.map.MessageType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean boolValue_ ;
    /**
     * <code>bool boolValue = 1;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      return boolValue_;
    }
    /**
     * <code>bool boolValue = 1;</code>
     * @param value The boolValue to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValue(boolean value) {
      
      boolValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolValue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValue() {
      
      boolValue_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object stringValue_ = "";
    /**
     * <code>string stringValue = 2;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stringValue = 2;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stringValue = 2;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stringValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stringValue = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      
      stringValue_ = getDefaultInstance().getStringValue();
      onChanged();
      return this;
    }
    /**
     * <code>string stringValue = 2;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stringValue_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytesValue = 3;</code>
     * @return The bytesValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesValue() {
      return bytesValue_;
    }
    /**
     * <code>bytes bytesValue = 3;</code>
     * @param value The bytesValue to set.
     * @return This builder for chaining.
     */
    public Builder setBytesValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bytesValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytesValue = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesValue() {
      
      bytesValue_ = getDefaultInstance().getBytesValue();
      onChanged();
      return this;
    }

    private int int32Value_ ;
    /**
     * <code>int32 int32Value = 4;</code>
     * @return The int32Value.
     */
    @java.lang.Override
    public int getInt32Value() {
      return int32Value_;
    }
    /**
     * <code>int32 int32Value = 4;</code>
     * @param value The int32Value to set.
     * @return This builder for chaining.
     */
    public Builder setInt32Value(int value) {
      
      int32Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int32Value = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt32Value() {
      
      int32Value_ = 0;
      onChanged();
      return this;
    }

    private int fixed32Value_ ;
    /**
     * <code>fixed32 fixed32Value = 5;</code>
     * @return The fixed32Value.
     */
    @java.lang.Override
    public int getFixed32Value() {
      return fixed32Value_;
    }
    /**
     * <code>fixed32 fixed32Value = 5;</code>
     * @param value The fixed32Value to set.
     * @return This builder for chaining.
     */
    public Builder setFixed32Value(int value) {
      
      fixed32Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 fixed32Value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed32Value() {
      
      fixed32Value_ = 0;
      onChanged();
      return this;
    }

    private int uint32Value_ ;
    /**
     * <code>uint32 uint32Value = 6;</code>
     * @return The uint32Value.
     */
    @java.lang.Override
    public int getUint32Value() {
      return uint32Value_;
    }
    /**
     * <code>uint32 uint32Value = 6;</code>
     * @param value The uint32Value to set.
     * @return This builder for chaining.
     */
    public Builder setUint32Value(int value) {
      
      uint32Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uint32Value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32Value() {
      
      uint32Value_ = 0;
      onChanged();
      return this;
    }

    private long int64Value_ ;
    /**
     * <code>int64 int64Value = 7;</code>
     * @return The int64Value.
     */
    @java.lang.Override
    public long getInt64Value() {
      return int64Value_;
    }
    /**
     * <code>int64 int64Value = 7;</code>
     * @param value The int64Value to set.
     * @return This builder for chaining.
     */
    public Builder setInt64Value(long value) {
      
      int64Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 int64Value = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64Value() {
      
      int64Value_ = 0L;
      onChanged();
      return this;
    }

    private long fixed64Value_ ;
    /**
     * <code>fixed64 fixed64Value = 8;</code>
     * @return The fixed64Value.
     */
    @java.lang.Override
    public long getFixed64Value() {
      return fixed64Value_;
    }
    /**
     * <code>fixed64 fixed64Value = 8;</code>
     * @param value The fixed64Value to set.
     * @return This builder for chaining.
     */
    public Builder setFixed64Value(long value) {
      
      fixed64Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 fixed64Value = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed64Value() {
      
      fixed64Value_ = 0L;
      onChanged();
      return this;
    }

    private long uint64Value_ ;
    /**
     * <code>uint64 uint64Value = 9;</code>
     * @return The uint64Value.
     */
    @java.lang.Override
    public long getUint64Value() {
      return uint64Value_;
    }
    /**
     * <code>uint64 uint64Value = 9;</code>
     * @param value The uint64Value to set.
     * @return This builder for chaining.
     */
    public Builder setUint64Value(long value) {
      
      uint64Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64Value = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64Value() {
      
      uint64Value_ = 0L;
      onChanged();
      return this;
    }

    private float floatValue_ ;
    /**
     * <code>float floatValue = 10;</code>
     * @return The floatValue.
     */
    @java.lang.Override
    public float getFloatValue() {
      return floatValue_;
    }
    /**
     * <code>float floatValue = 10;</code>
     * @param value The floatValue to set.
     * @return This builder for chaining.
     */
    public Builder setFloatValue(float value) {
      
      floatValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float floatValue = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatValue() {
      
      floatValue_ = 0F;
      onChanged();
      return this;
    }

    private double doubleValue_ ;
    /**
     * <code>double doubleValue = 11;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      return doubleValue_;
    }
    /**
     * <code>double doubleValue = 11;</code>
     * @param value The doubleValue to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleValue(double value) {
      
      doubleValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double doubleValue = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleValue() {
      
      doubleValue_ = 0D;
      onChanged();
      return this;
    }

    private int enumValue_ = 0;
    /**
     * <code>.ref.parse.EnumType enumValue = 12;</code>
     * @return The enum numeric value on the wire for enumValue.
     */
    @java.lang.Override public int getEnumValueValue() {
      return enumValue_;
    }
    /**
     * <code>.ref.parse.EnumType enumValue = 12;</code>
     * @param value The enum numeric value on the wire for enumValue to set.
     * @return This builder for chaining.
     */
    public Builder setEnumValueValue(int value) {
      
      enumValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ref.parse.EnumType enumValue = 12;</code>
     * @return The enumValue.
     */
    @java.lang.Override
    public com.examples.protobuf.map.EnumType getEnumValue() {
      @SuppressWarnings("deprecation")
      com.examples.protobuf.map.EnumType result = com.examples.protobuf.map.EnumType.valueOf(enumValue_);
      return result == null ? com.examples.protobuf.map.EnumType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ref.parse.EnumType enumValue = 12;</code>
     * @param value The enumValue to set.
     * @return This builder for chaining.
     */
    public Builder setEnumValue(com.examples.protobuf.map.EnumType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      enumValue_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ref.parse.EnumType enumValue = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnumValue() {
      
      enumValue_ = 0;
      onChanged();
      return this;
    }

    private com.examples.protobuf.map.ReferenceMessageType referenceValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.examples.protobuf.map.ReferenceMessageType, com.examples.protobuf.map.ReferenceMessageType.Builder, com.examples.protobuf.map.ReferenceMessageTypeOrBuilder> referenceValueBuilder_;
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     * @return Whether the referenceValue field is set.
     */
    public boolean hasReferenceValue() {
      return referenceValueBuilder_ != null || referenceValue_ != null;
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     * @return The referenceValue.
     */
    public com.examples.protobuf.map.ReferenceMessageType getReferenceValue() {
      if (referenceValueBuilder_ == null) {
        return referenceValue_ == null ? com.examples.protobuf.map.ReferenceMessageType.getDefaultInstance() : referenceValue_;
      } else {
        return referenceValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    public Builder setReferenceValue(com.examples.protobuf.map.ReferenceMessageType value) {
      if (referenceValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referenceValue_ = value;
        onChanged();
      } else {
        referenceValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    public Builder setReferenceValue(
        com.examples.protobuf.map.ReferenceMessageType.Builder builderForValue) {
      if (referenceValueBuilder_ == null) {
        referenceValue_ = builderForValue.build();
        onChanged();
      } else {
        referenceValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    public Builder mergeReferenceValue(com.examples.protobuf.map.ReferenceMessageType value) {
      if (referenceValueBuilder_ == null) {
        if (referenceValue_ != null) {
          referenceValue_ =
            com.examples.protobuf.map.ReferenceMessageType.newBuilder(referenceValue_).mergeFrom(value).buildPartial();
        } else {
          referenceValue_ = value;
        }
        onChanged();
      } else {
        referenceValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    public Builder clearReferenceValue() {
      if (referenceValueBuilder_ == null) {
        referenceValue_ = null;
        onChanged();
      } else {
        referenceValue_ = null;
        referenceValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    public com.examples.protobuf.map.ReferenceMessageType.Builder getReferenceValueBuilder() {
      
      onChanged();
      return getReferenceValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    public com.examples.protobuf.map.ReferenceMessageTypeOrBuilder getReferenceValueOrBuilder() {
      if (referenceValueBuilder_ != null) {
        return referenceValueBuilder_.getMessageOrBuilder();
      } else {
        return referenceValue_ == null ?
            com.examples.protobuf.map.ReferenceMessageType.getDefaultInstance() : referenceValue_;
      }
    }
    /**
     * <code>.ref.parse.ReferenceMessageType referenceValue = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.examples.protobuf.map.ReferenceMessageType, com.examples.protobuf.map.ReferenceMessageType.Builder, com.examples.protobuf.map.ReferenceMessageTypeOrBuilder> 
        getReferenceValueFieldBuilder() {
      if (referenceValueBuilder_ == null) {
        referenceValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.examples.protobuf.map.ReferenceMessageType, com.examples.protobuf.map.ReferenceMessageType.Builder, com.examples.protobuf.map.ReferenceMessageTypeOrBuilder>(
                getReferenceValue(),
                getParentForChildren(),
                isClean());
        referenceValue_ = null;
      }
      return referenceValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ref.parse.MessageType)
  }

  // @@protoc_insertion_point(class_scope:ref.parse.MessageType)
  private static final com.examples.protobuf.map.MessageType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.examples.protobuf.map.MessageType();
  }

  public static com.examples.protobuf.map.MessageType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageType>
      PARSER = new com.google.protobuf.AbstractParser<MessageType>() {
    @java.lang.Override
    public MessageType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.examples.protobuf.map.MessageType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

