// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

package com.examples.protobuf.map;

/**
 * Protobuf type {@code ref.parse.ReferenceMessageType}
 */
public final class ReferenceMessageType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ref.parse.ReferenceMessageType)
    ReferenceMessageTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReferenceMessageType.newBuilder() to construct.
  private ReferenceMessageType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReferenceMessageType() {
    string_ = "";
    list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReferenceMessageType();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReferenceMessageType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            string_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              list_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            list_.add(s);
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              map_ = com.google.protobuf.MapField.newMapField(
                  MapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            map__ = input.readMessage(
                MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            map_.getMutableMap().put(
                map__.getKey(), map__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        list_ = list_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.examples.protobuf.map.Map.internal_static_ref_parse_ReferenceMessageType_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.examples.protobuf.map.Map.internal_static_ref_parse_ReferenceMessageType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.examples.protobuf.map.ReferenceMessageType.class, com.examples.protobuf.map.ReferenceMessageType.Builder.class);
  }

  public static final int STRING_FIELD_NUMBER = 1;
  private volatile java.lang.Object string_;
  /**
   * <code>string string = 1;</code>
   * @return The string.
   */
  @java.lang.Override
  public java.lang.String getString() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      string_ = s;
      return s;
    }
  }
  /**
   * <code>string string = 1;</code>
   * @return The bytes for string.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      string_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIST_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList list_;
  /**
   * <code>repeated string list = 2;</code>
   * @return A list containing the list.
   */
  public com.google.protobuf.ProtocolStringList
      getListList() {
    return list_;
  }
  /**
   * <code>repeated string list = 2;</code>
   * @return The count of list.
   */
  public int getListCount() {
    return list_.size();
  }
  /**
   * <code>repeated string list = 2;</code>
   * @param index The index of the element to return.
   * @return The list at the given index.
   */
  public java.lang.String getList(int index) {
    return list_.get(index);
  }
  /**
   * <code>repeated string list = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the list at the given index.
   */
  public com.google.protobuf.ByteString
      getListBytes(int index) {
    return list_.getByteString(index);
  }

  public static final int MAP_FIELD_NUMBER = 3;
  private static final class MapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.examples.protobuf.map.Map.internal_static_ref_parse_ReferenceMessageType_MapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> map_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMap() {
    if (map_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapDefaultEntryHolder.defaultEntry);
    }
    return map_;
  }

  public int getMapCount() {
    return internalGetMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */

  @java.lang.Override
  public boolean containsMap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMap() {
    return getMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
    return internalGetMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, string_);
    }
    for (int i = 0; i < list_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, list_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMap(),
        MapDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, string_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < list_.size(); i++) {
        dataSize += computeStringSizeNoTag(list_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getListList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, map__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.examples.protobuf.map.ReferenceMessageType)) {
      return super.equals(obj);
    }
    com.examples.protobuf.map.ReferenceMessageType other = (com.examples.protobuf.map.ReferenceMessageType) obj;

    if (!getString()
        .equals(other.getString())) return false;
    if (!getListList()
        .equals(other.getListList())) return false;
    if (!internalGetMap().equals(
        other.internalGetMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STRING_FIELD_NUMBER;
    hash = (53 * hash) + getString().hashCode();
    if (getListCount() > 0) {
      hash = (37 * hash) + LIST_FIELD_NUMBER;
      hash = (53 * hash) + getListList().hashCode();
    }
    if (!internalGetMap().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.examples.protobuf.map.ReferenceMessageType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.examples.protobuf.map.ReferenceMessageType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ref.parse.ReferenceMessageType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ref.parse.ReferenceMessageType)
      com.examples.protobuf.map.ReferenceMessageTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.examples.protobuf.map.Map.internal_static_ref_parse_ReferenceMessageType_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.examples.protobuf.map.Map.internal_static_ref_parse_ReferenceMessageType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.examples.protobuf.map.ReferenceMessageType.class, com.examples.protobuf.map.ReferenceMessageType.Builder.class);
    }

    // Construct using com.examples.protobuf.map.ReferenceMessageType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      string_ = "";

      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.examples.protobuf.map.Map.internal_static_ref_parse_ReferenceMessageType_descriptor;
    }

    @java.lang.Override
    public com.examples.protobuf.map.ReferenceMessageType getDefaultInstanceForType() {
      return com.examples.protobuf.map.ReferenceMessageType.getDefaultInstance();
    }

    @java.lang.Override
    public com.examples.protobuf.map.ReferenceMessageType build() {
      com.examples.protobuf.map.ReferenceMessageType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.examples.protobuf.map.ReferenceMessageType buildPartial() {
      com.examples.protobuf.map.ReferenceMessageType result = new com.examples.protobuf.map.ReferenceMessageType(this);
      int from_bitField0_ = bitField0_;
      result.string_ = string_;
      if (((bitField0_ & 0x00000001) != 0)) {
        list_ = list_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.list_ = list_;
      result.map_ = internalGetMap();
      result.map_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.examples.protobuf.map.ReferenceMessageType) {
        return mergeFrom((com.examples.protobuf.map.ReferenceMessageType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.examples.protobuf.map.ReferenceMessageType other) {
      if (other == com.examples.protobuf.map.ReferenceMessageType.getDefaultInstance()) return this;
      if (!other.getString().isEmpty()) {
        string_ = other.string_;
        onChanged();
      }
      if (!other.list_.isEmpty()) {
        if (list_.isEmpty()) {
          list_ = other.list_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureListIsMutable();
          list_.addAll(other.list_);
        }
        onChanged();
      }
      internalGetMutableMap().mergeFrom(
          other.internalGetMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.examples.protobuf.map.ReferenceMessageType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.examples.protobuf.map.ReferenceMessageType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object string_ = "";
    /**
     * <code>string string = 1;</code>
     * @return The string.
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string = 1;</code>
     * @return The bytes for string.
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string = 1;</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      string_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      
      string_ = getDefaultInstance().getString();
      onChanged();
      return this;
    }
    /**
     * <code>string string = 1;</code>
     * @param value The bytes for string to set.
     * @return This builder for chaining.
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      string_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        list_ = new com.google.protobuf.LazyStringArrayList(list_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string list = 2;</code>
     * @return A list containing the list.
     */
    public com.google.protobuf.ProtocolStringList
        getListList() {
      return list_.getUnmodifiableView();
    }
    /**
     * <code>repeated string list = 2;</code>
     * @return The count of list.
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 2;</code>
     * @param index The index of the element to return.
     * @return The list at the given index.
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the list at the given index.
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }
    /**
     * <code>repeated string list = 2;</code>
     * @param index The index to set the value at.
     * @param value The list to set.
     * @return This builder for chaining.
     */
    public Builder setList(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
      list_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     * @param value The list to add.
     * @return This builder for chaining.
     */
    public Builder addList(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
      list_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     * @param values The list to add.
     * @return This builder for chaining.
     */
    public Builder addAllList(
        java.lang.Iterable<java.lang.String> values) {
      ensureListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, list_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearList() {
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     * @param value The bytes of the list to add.
     * @return This builder for chaining.
     */
    public Builder addListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureListIsMutable();
      list_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMap() {
      onChanged();;
      if (map_ == null) {
        map_ = com.google.protobuf.MapField.newMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      if (!map_.isMutable()) {
        map_ = map_.copy();
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */

    @java.lang.Override
    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMap() {
      internalGetMutableMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */

    public Builder removeMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMap() {
      return internalGetMutableMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */
    public Builder putMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; map = 3;</code>
     */

    public Builder putAllMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ref.parse.ReferenceMessageType)
  }

  // @@protoc_insertion_point(class_scope:ref.parse.ReferenceMessageType)
  private static final com.examples.protobuf.map.ReferenceMessageType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.examples.protobuf.map.ReferenceMessageType();
  }

  public static com.examples.protobuf.map.ReferenceMessageType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReferenceMessageType>
      PARSER = new com.google.protobuf.AbstractParser<ReferenceMessageType>() {
    @java.lang.Override
    public ReferenceMessageType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReferenceMessageType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReferenceMessageType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReferenceMessageType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.examples.protobuf.map.ReferenceMessageType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

